### ISSUE TITLE
🙀 Emjoji in table not working in Github Enterprise

### ISSUE THREAD

**Issue by mtitolo** [nakiostudio/xcov#35]
For some reason, the unknown boxes come up for all the emojis in the table:
![screen shot 2016-08-19 at 5 45 47 pm](https://cloud.githubusercontent.com/assets/763698/17827631/0aa35632-6635-11e6-970d-782a47663581.png)

Emojis for no changes work fine:
![screen shot 2016-08-19 at 5 48 16 pm](https://cloud.githubusercontent.com/assets/763698/17827636/3242b2aa-6635-11e6-865c-23fef028b7a9.png)

The emojis display correct in the comment editor:
![screen shot 2016-08-19 at 5 51 14 pm](https://cloud.githubusercontent.com/assets/763698/17827661/abc5a704-6635-11e6-99b2-1fb4c0c89978.png)

And obviously I can replace the emojis and they work fine.

This is using GH Enterprise 2.6. HTML appears to be the same and the emoji is there when I inspect the source. Just won't display properly the first time when coming from CI 😢

**Comment by nakiostudio** [comment]
Hi @mtitolo 👋 

Thank you for reporting! I think the problem is due to an encoding issue with your CI. We use GH Enterprise 2.6 at @lyst and we haven't had any problem so far. Which CI system are you using?

Anyway, I'm going to submit a PR replacing the unicode characters for github emoji codes `: skull :`, `: no_entry_sign :`, etc that should solver our issue.

**Comment by nakiostudio** [comment]
Hi again @mtitolo 👋 

I've just released `0.11.1` which should fix your problem. Let me know if it actually does it!
