### ISSUE TITLE
does it support coveralls?

### ISSUE THREAD

**Issue by huminzhi** [nakiostudio/xcov#64]

**Comment by thelvis4** [comment]
@huminzhi Currently, it doesn't support coveralls, but it's a great feature we could implement eventually. It cannot be done quickly because this feature depends on the information about each line in a file and we don't have that yet (it's somehow related to #51).

But it's a feature I would definitely love to work on when I find some time. 😊

**Comment by huminzhi** [comment]
Thank you very much @thelvis4 for replying..
Quick dumb question.. is branch coverage or line coverage provided by xcov?

**Comment by thelvis4** [comment]
@huminzhi Basically, `xcov` uses the data provided by Xcode, and Xcode gives us line coverage. 
I would prefer to have branch coverage provided by Xcode, though. 😞

**Comment by nakiostudio** [comment]
It does now :)
